### ISSUE TITLE
Issue with numerics in json variation types

### ISSUE THREAD

**Issue by andrewescutia** [launchdarkly/flutter-client-sdk#14]
**Describe the bug**
It appears that there may be an inconsistency in how the package handles json variation types that contain number values.

Take the following json variation:
```
{
  "disabledIds": [
    12345
  ]
}
```

ios will return it as is: 12345
android will assume it to be a double: 12345.0

This causes an additional casting step that only occurs on android as Flutter assumes it to be a double type. I believe this may be due to line 170 in LaunchdarklyFlutterClientSdkPlugin.kt?

Should that add a check to determine whether its an int type or not before performing the conversion?

**To reproduce**
Create a flag with a json variation that contains a numeric value similar to what is noted above. Retrieve the flag in both android and ios and note the difference.

**Expected behavior**
Hope that both are returned in a similar manner

**SDK version**
launchdarkly_flutter_client_sdk 1.0.0

**Comment by louis-launchdarkly** [comment]
Hello @andrewescutia, thank you for reporting this to us. I have filed an issue and we will investigate this.

_Filed Internally as 151058_
