### ISSUE TITLE
Consider upgrading the package "package_info_plus" to latest as "launchdarkly_flutter_client_sdk" uses very old version

### ISSUE THREAD

**Issue by SatishKumarRaizada** [launchdarkly/flutter-client-sdk#153]
You can try one of the following suggestions to make the pubspec resolve:
* Consider downgrading your constraint on launchdarkly_flutter_client_sdk: flutter pub add launchdarkly_flutter_client_sdk:^3.1.0
* Consider downgrading your constraint on package_info_plus: flutter pub add package_info_plus:^4.2.0
exit code 1

**Comment by kinyoklion** [comment]
Hello @SatishKumarRaizada,

I am not completely sure what the request is here? The flutter_client_sdk 4.x supports up to 6.0.0 (22 days old) of the package_info_plus package. It does not yet support 7.0.0 (which came out 2 days ago.)

4.2.0 is the oldest version it supports. This is the version constraint:
```
package_info_plus: ">=4.2.0 <7.0.0"
```

Is the request to increase that range to:
package_info_plus: ">=4.2.0 <8.0.0"

Thank you,
Ryan

**Comment by maxlapides** [comment]
Just wanted to note here that, since this issue was filed, `package_info_plus` version 8.0.0 was released

**Comment by kinyoklion** [comment]
We did already release one that supports 7, but I never got an answer to the question in this thread so I didn't close this issue. If 8 is compatible with 7, then you can override the version locally until we have had time to update and release.

**Comment by kinyoklion** [comment]
4.6 has been released which supports 8.0.0.
