### ISSUE TITLE
Compilation issue on Kotlin 1.7.0

### ISSUE THREAD

**Issue by maxlapides** [launchdarkly/flutter-client-sdk#16]
**Describe the bug**
Error on `flutter build`:

```
Error: e: /opt/hostedtoolcache/flutter/.pub-cache/hosted/pub.dartlang.org/launchdarkly_flutter_client_sdk-1.0.0/android/src/main/kotlin/com/launchdarkly/launchdarkly_flutter_client_sdk/LaunchdarklyFlutterClientSdkPlugin.kt: (195, 7): 'when' expression must be exhaustive, add necessary 'OFF', 'TARGET_MATCH', 'null' branches or 'else' branch instead
```

**To reproduce**
In your Flutter app, upgrade `ext.kotlin_version` in `android/build.gradle` to `'1.7.0'`

**Expected behavior**
App compiles

**SDK version**
`1.0.0`

**Language version, developer tools**
Flutter 3.0.2

**Comment by kinyoklion** [comment]
Hello @maxlapides,

It seems that the default behavior of the compiler has changed in 1.7. I think it was this change: https://youtrack.jetbrains.com/issue/KT-47709/Make-when-statements-with-enum-sealed-and-Boolean-subjects-exhaustive-by-default

We will look into it.

_Filed internally as 15691_

Thank you,
Ryan

**Comment by kinyoklion** [comment]
Hello @maxlapides,

This should be resolve by release `1.1.2`.

Thank you!
-Ryan

**Comment by maxlapides** [comment]
Thanks for the fix!
