### ISSUE TITLE
Upgrade device_info_plus to version 11

### ISSUE THREAD

**Issue by mattbajorek** [launchdarkly/flutter-client-sdk#179]
**Is this a support request?**
Yes

**Describe the bug**
device_info_plus package is now at version 11 and there packages that use version 11. This creates an incompatibility with laundarkly_flutter_client_sdk

**To reproduce**
Add livekit_client: ^2.3.2 to pubspec.yaml

**Comment by kinyoklion** [comment]
@mattbajorek Thank you for the report.

_Filed internally as SDK-1002_
