### ISSUE TITLE
Null-safety

### ISSUE THREAD

**Issue by QuirijnGB** [launchdarkly/flutter-client-sdk#2]
Since Flutter 2 has been released this SDK needs to be updated to support null-safety.
https://flutter.dev/docs/null-safety

**Comment by gwhelanLD** [comment]
Hi @QuirijnGB,

We appreciate the notice, we're looking at including this upgrade for our next beta release. 

Thanks,
@gwhelanLD

**Comment by SAGARSURI** [comment]
Hey @gwhelanLD when is the next release happening? We are planning to use LaunchDarkly in our flutter app.

**Comment by gwhelanLD** [comment]
I'm happy to announce that the [0.2.0 release](https://github.com/launchdarkly/flutter-client-sdk/releases/tag/0.2.0) of the SDK now supports null-safety. Thanks for your feedback on this beta SDK!

Thanks,
@gwhelanLD
