### ISSUE TITLE
Clashes with newer Android Gradle plugin and Kotlin verions

### ISSUE THREAD

**Issue by dimitar-zabaznoski** [launchdarkly/flutter-client-sdk#23]
**Describe the bug**
The client SDK's android Kotlin and Android Gradle Plugin versions clash with projects with newer kotlin and gradle plugin versions at build time.

**To reproduce**
1. Set a higher (1.7.10) version of Kotlin and use the newer Android Gradle Plugin (7.3.1) in `/android/build.gradle` 
```
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        
   ...     
```
2. Try to build/run the flutter app with the launch darkly client sdk added as dependency. The build will fail.

**Expected behavior**
The SDK should be compatible with newer versions of Kotlin and the Gradle Plugin

**Logs**
Build error:
```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':launchdarkly_flutter_client_sdk' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.32
```

**SDK version**
`launchdarkly_flutter_client_sdk: ^1.1.4`

**Language version, developer tools**
```
dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10"
```

**OS/platform**
Android 12

**Comment by kinyoklion** [comment]
Hello @dimitar-zabaznoski,

Thanks for raising this issue.

_Filed internally as 175305_

Thank you,
Ryan
