### ISSUE TITLE
registerFeatureFlagListener not working

### ISSUE THREAD

**Issue by akanksha820** [launchdarkly/flutter-client-sdk#5]
When i hot restart my flutter application, the listeners seemed to have stopped working. I do not receive any updates related to my feature flag

Can i use the start method of the LDClient whenever my app starts?

**launchdarkly_flutter_client_sdk/SwiftLaunchdarklyFlutterClientSdkPlugin.swift:152: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Lost connection to device.**

The application crashes when i restart the app with await LDClient.start() since it received the missed update from the launchDarkly this time

**Comment by bwoskow-ld** [comment]
Hi @akanksha820 ,

We'll look into this and get back to you.

_Filed internally as 117465._

**Comment by gwhelanLD** [comment]
Hi @akanksha820,

With a hot-restart we can't maintain the registered flag listeners, but we've made some changes in the [0.3.0 release](https://github.com/launchdarkly/flutter-client-sdk/releases/tag/0.3.0) that may make it easier to handle listeners when using hot-restarts. You should be able to safely use `LDClient.start` whenever your application starts (including a hot-restart) now, but you will still need to register the listeners after the hot-restart. I'll close this issue as you should be able to use flag listeners with hot-restarts at this point, but feel free to re-open if you run into further issues.

Thanks,
@gwhelanLD
