### ISSUE TITLE
Update LunchDarkly Value 

### ISSUE THREAD

**Issue by tazik561** [launchdarkly/flutter-client-sdk#52]
Is it possible to make an update feature flag? As an example I have a FF with a true value, Is it possible to make it false?

**Comment by tazik561** [comment]
> @tazik561 , could you elaborate more? The most common use case of Feature Flags is to be able to update them to change their values. [Here are some relevant docs.](https://docs.launchdarkly.com/home/flags/toggle)

Is it possible to do that by LDClient or I have to use API? https://www.postman.com/api-evangelist/workspace/launchdarkly/request/35240-e7e4da3e-1962-46ee-893e-76ba5d78df10

**Comment by tanderson-ld** [comment]
[The hello-flutter repo shows how to evaluate a feature flag through the LDClient class and how to receive asynchronous flag changes.](https://github.com/launchdarkly/hello-flutter/blob/main/lib/main.dart)

**Comment by tazik561** [comment]
> [The hello-flutter repo shows how to evaluate a feature flag through the LDClient class and how to receive asynchronous flag changes.](https://github.com/launchdarkly/hello-flutter/blob/main/lib/main.dart)

I mean I want to make the feature flag off or on, No, receive flag changes, or evaluate a feature flag . Imagine I have a FF with a false value, I want to make it off by  LDClient from mobile application.

**Comment by tanderson-ld** [comment]
Oh I see.  No there is no way to affect the flag rules on the cloud from the client side SDK.

**Comment by tazik561** [comment]
> Oh I see. No there is no way to affect the flag rules on the cloud from the client side SDK.

So I have to use open API.
Thanks
