### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method start on channel launchdarkly_flutter_client_sdk)

### ISSUE THREAD

**Issue by mattbajorek** [launchdarkly/flutter-client-sdk#57]
**Describe the bug**
`.start` method immediately errors out with MissingPluginException on Android for both simulator and physical device. Is there an extra SDK integration needed?

**To reproduce**
1. Add `launchdarkly_flutter_client_sdk: ^3.0.1` to pubspec.yaml
2. After WidgetsFlutterBinding.ensureInitialized(); add:

```dart
final ldConfig = LDConfigBuilder(launchDarklyKey, AutoEnvAttributes.Enabled).build();
final ldContext = LDContextBuilder().build();
await LDClient.start(ldConfig, ldContext);
```

**Expected behavior**

**Logs**
E/flutter (17494): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method start on channel launchdarkly_flutter_client_sdk)
E/flutter (17494): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter (17494): <asynchronous suspension>
E/flutter (17494): #1      LDClient.startWithContext (package:launchdarkly_flutter_client_sdk/launchdarkly_flutter_client_sdk.dart:106:5)
E/flutter (17494): <asynchronous suspension>

**Flutter version**
\>=3.0.6 <4.0.0

**SDK version**
4.0.1 and 2.1.0

**OS/platform**
Android

**Comment by tanderson-ld** [comment]
Hi @mattbajorek , the current version of our Flutter SDK wraps our iOS and Android SDKs as native plugins.  This sounds like a good place to start the investigation.  Have you been able to run our [hello-flutter](https://github.com/launchdarkly/hello-flutter) repo?

**Comment by tanderson-ld** [comment]
Can you confirm the presence of the android folder in the Flutter Plugins section of your project?  (This is in Android Studio).

![image](https://github.com/launchdarkly/flutter-client-sdk/assets/127344469/a83ebc2c-ef26-4c16-afbb-95443767c279)

**Comment by mattbajorek** [comment]
If these are wrappers are there any specific Android or iOS changes needed? I tried following the Android documents by adding:

```grade
implementation 'com.launchdarkly:launchdarkly-android-client-sdk:5.0.0'
```

to `app/build.gradle` and

```kotlin
import com.launchdarkly.sdk.*
import com.launchdarkly.sdk.android.*
```

to `MainActivity.kt` with no avail.

**Comment by tanderson-ld** [comment]
You shouldn't need to make any iOS / Android file changes.  I just wanted to confirm the dependency that was fetched does have the native folders.

**Comment by tanderson-ld** [comment]
Have you been able to run our [hello-flutter](https://github.com/launchdarkly/hello-flutter) repo?

**Comment by mattbajorek** [comment]
I am able to run the hello-flutter repo. I found the issue for anyone else is struggling with this. The `LDContextBuilder` must have a kind set. By following the example with `builder.kind('user', 'user-key-123abc');` the issue went away.

Is there a way to initially not have a kind and then add a kind as user information is provided dynamically?

**Comment by tanderson-ld** [comment]
Ah, I see what happened.  We have an existing discrepancy between our Android and iOS SDK where the Android SDK must be provided a non-empty context with a key.  We plan to fix the bug Android side when time permits.  That error is very cryptic.

I recommend using an anonymous context for the period of time where you have no user information.

https://docs.launchdarkly.com/sdk/features/anonymous#flutter

**Comment by tanderson-ld** [comment]
Thank you for tracking down the cause.  I missed that a kind was missing in the original code snippet.

**Comment by tanderson-ld** [comment]
Have you turned the targeting for that flag to On?  Sometimes this is a common culprit.

![image](https://github.com/launchdarkly/flutter-client-sdk/assets/127344469/5414734b-3a11-4d2f-b5d4-b3725fbe5cfb)

**Comment by mattbajorek** [comment]
Yes we have it on. We can validate that on the web SDK. We have multiple feature flags and they all come back false for Flutter, but true for web.

**Comment by mattbajorek** [comment]
Also calling:

```dart
final flags = await LDClient.allFlags();
```

Properly returns all the names of our tags, but all of them are set as false.

**Comment by tanderson-ld** [comment]
I just tested a killSwitch template locally with the flutter SDK, and it is working on my machine.  Do you have any interesting configurations with respect to network permissions, storage permissioning, VPN?  Trying to develop a few more theories.

**Comment by mattbajorek** [comment]
Ahh I found it. I was using the prod environment key which was setup but the flags weren't set yet. We can close this.

**Comment by tanderson-ld** [comment]
No worries!  We've all been there.  If you need other higher level support requests, you can [open a support ticket here](https://support.launchdarkly.com/hc/en-us/requests/new).  If you run into any more nitty gritty code issues / suspected bugs, feel free to open another issue.  Thanks.

**Comment by Mik77o** [comment]
@tanderson-ld, I confirm this statement you added once: _We have an existing discrepancy between our Android and iOS SDK where the Android SDK must be provided a non-empty context with a key_. A non-empty value solves this problem.
​
