### ISSUE TITLE
Need Flutter Web Support

### ISSUE THREAD

**Issue by aniketudeshmukh** [launchdarkly/flutter-client-sdk#6]
Please add Flutter Web support. Currently flutter sdk seems to support only iOS and Android.

**Comment by bwoskow-ld** [comment]
Hi @aniketudeshmukh,

Thank you for your interest in our Flutter SDK. At the moment we don't have plans to expand SDK support for web environments. Our upcoming 1.0.0 release will only support iOS and Android. The reason for this is because, as currently implemented, the SDK wraps native modules provided by LaunchDarkly's iOS and Android SDKs. While we also have a JavaScript-based web SDK which could theoretically be additionally wrapped, the JS SDK has some behavioral inconsistencies when compared with our mobile SDKs and we do not want to introduce such platform-specific inconsistencies into a single SDK.

In the future we may choose to expand support but we cannot commit to this nor any timeline at the moment. In the meantime I'm taking note of this request in our internal feature request tracker.

Cheers,
@bwoskow-ld

**Comment by aniketudeshmukh** [comment]
Thanks Ben for your reply. I understand your point.

We are one of the early adopters of Flutter web. We have single source code
that works on mobile and web. We are evaluating LaunchDarkly for our app.
It would have been really great if flutter SDK supported both mobile and
web.

We are looking at LaunchDarkly to be our single solution for managing
feature flags across front end (flutter mobile + flutter web) and backend
(go).

Not having flutter web support might be a deal breaker for us.

Can you please guide us how can we somehow get LaunchDarkly to work on
flutter web too as we have single code base for web and mobile?

Would really appreciate your inputs on this.

Regards,
@aniketudeshmukh

**Comment by bwoskow-ld** [comment]
We don't have a workaround for this at the moment but will continue to think about and consider this.

**Comment by RTodorov** [comment]
For visibility, this is also a deal breaker for me. I assume this problem will only grow bigger as flutter web is becoming more mature and being adopted by more people.

**Comment by stefannovak** [comment]
Managed to get LaunchDarkly working for mobile and web with flutter, using the JavaScript SDK for web only. Was a bit of a nightmare but it is possible. Having the flutter SDK work for Web would be a life saver.

**Comment by ankit-k-gupta-maersk** [comment]
> Managed to get LaunchDarkly working for mobile and web with flutter, using the JavaScript SDK for web only. Was a bit of a nightmare but it is possible. Having the flutter SDK work for Web would be a life saver.

@stefannovak Would it possible for you to share the piece of code that you used to overcome this limitation? It could be really helpful.

**Comment by carmentorres-kueski** [comment]
+1 this being a deal breaker, I think you should really put this issue your radar

**Comment by ezet** [comment]
+1 this is a deal breaker for us to. We we're about to set up a subscription after trialing this, but without web-support this is a no-go. Back to searching then.. :/

**Comment by alexdaniels11** [comment]
This is a deal breaker for us as well. [bwoskow-ld](https://github.com/bwoskow-ld)

**Comment by etbrow** [comment]
Adding to the "this is a deal breaker" count

**Comment by kevmoo** [comment]
If you have an account with @launchdarkly it might be worth opening a ticket to push here: https://support.launchdarkly.com/hc/en-us/requests/new

**Comment by etbrow** [comment]
We have and unfortunately were told there's no current plan to support it.

**Comment by CUFRE001** [comment]
One of the comments says that there is a workaround using the JavaScript SDK. Do you have an example of how it can be implemented?

**Comment by lucasmpr** [comment]
I've made a simple barebones script to begin with using the SDK. in flutter web It's not in the right "plugin" architechture but seems to work.  

1. Add the launchdarlky sdk to index.html
```
<script src="https://unpkg.com/launchdarkly-js-client-sdk@3"></script>
```
2. Use the following code ;)
https://gist.github.com/lucasmpr/f8fd861c84fda2d21f43296d1eaaf15c

**Comment by kinyoklion** [comment]
Version 4.0+ of the SDK supports the web target.

Thank you,
Ryan

**Comment by jturak-rbi** [comment]
We've been waiting for this feature for quite some time, so glad it's finally here! Ty! We were able to successfully upgrade to this package and use for web.

For those curious, initially we ran into a timeout issue getting the LDClient to start in web. Took some digging into the package code and saw a comment about streaming not being available for web, so we changed the initial connection mode to polling and it worked. 

`final LDConfig config = LDConfig(
        ldClientId,
        AutoEnvAttributes.enabled,
        dataSourceConfig: DataSourceConfig(
          initialConnectionMode: ConnectionMode.polling,
        ),
      );`

**Comment by kinyoklion** [comment]
> We've been waiting for this feature for quite some time, so glad it's finally here! Ty! We were able to successfully upgrade to this package and use for web.
> 
> For those curious, initially we ran into a timeout issue getting the LDClient to start in web. Took some digging into the package code and saw a comment about streaming not being available for web, so we changed the initial connection mode to polling and it worked.
> 
> `final LDConfig config = LDConfig( ldClientId, AutoEnvAttributes.enabled, dataSourceConfig: DataSourceConfig( initialConnectionMode: ConnectionMode.polling, ), );`

Hey @jturak-rbi streaming should be available on the web as well. If you could provide the error messages you got that would be great.

Note that `useReport` + `streaming` is not supported, and it will use normal streaming.

**Comment by kinyoklion** [comment]
I am pleased to here you were able to upgrade and use it!

**Comment by jturak-rbi** [comment]
@kinyoklion Ah it must have been the useReport + streaming that I saw in the comment somewhere in the package code. Regardless, I'm not seeing an error getting thrown from the client in web, seems to be failing silently or getting stuck somewhere. I have timeouts of 30 seconds being set on the start and identify calls on the client. 

Web browser info
Chrome Version 121.0.6167.184 (Official Build) (arm64)

client ??= LDClient(config, context);

    if (client!.initialized) {
      await client!.identify(context).timeout(const Duration(seconds: 30));
    } else {
      await client!.start().timeout(const Duration(seconds: 30));
    }

**Comment by kinyoklion** [comment]
Thank you. I will take a look.

**Comment by kinyoklion** [comment]
@jturak-rbi I will try to isolate things some more, but so far I am unable to replicate.

I am seeing initialization in chrome within very small windows and not experiencing a timeout on either start or identify.

We could get extra data by running with the debug log level:
```
final LDConfig config = LDConfig(
      ldClientId,
      AutoEnvAttributes.enabled,
      dataSourceConfig: DataSourceConfig(
        initialConnectionMode: ConnectionMode.streaming,
      ),
      logger: LDLogger(level: LDLogLevel.debug)
    );
```

Based on (arm64) I assume an Apple Silicon mac? I will do some testing on an M1 mac.

Is there anything unique about your LaunchDarkly environment? Really large (many flags, large flags, etc.)?

Do you see the event source connection in the chrome debugger?

Do you see the same thing with the example application? The example application uses a 5 second timeout, but you should be able to see the result of an identify in much less than that.

Thank you,
Ryan

**Comment by kinyoklion** [comment]
@jturak-rbi 

Would it be possible to get the output of `flutter doctor` as well?

Thank you,
Ryan

**Comment by jturak-rbi** [comment]
@kinyoklion
No flags out of the usual imo. I think I see the stream connection in the console dev tools. 

Couple questions: 
- What do you consider really large flags? Or a large amount of flags? 
- Am I able to poll a streaming client? Ideal scenario is to setup the client, fetch all the flags, and then setup the streaming for flag updates the update the appropriate flag. Would I need to setup a polling client to get all the flags and then a separate streaming client to ingest the flag updates?
- Can you point me in the right direction where to setup some debugging points? I put some breakpoints in the ld_common_client.dart and it seems that the future in the _start function `return _startFuture!.then(_mapIdentifyStart); ` is never returned. But I'd like to dig deeper. 

I have a small hypothesis that it could be due to my computer's VPN/firewall and its interaction with streams, but not certain. 

I haven't had time to setup the example app, the architecture there is a bit different than our app. 

Flutter doctor: 
doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel [user-branch], 3.16.9, on macOS 14.3.1 23D60 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
[✓] Network resources

**Comment by kinyoklion** [comment]
> * What do you consider really large flags? Or a large amount of flags?

Something in the multi-megabyte territory. Everything should work fine, but I am looking for things out of the ordinary.

> * Am I able to poll a streaming client? Ideal scenario is to setup the client, fetch all the flags, and then setup the streaming for flag updates the update the appropriate flag. Would I need to setup a polling client to get all the flags and then a separate streaming client to ingest the flag updates?

Our streaming connection is just an SSE stream, which is basically an HTTP GET which remains open. Over that stream will be a "put" which is basically equivalent to doing a poll. Subsequently deltas will be sent to update the local state. These will also trigger your change listeners. In the future the relationship between these things may change, but currently there isn't a way to start a stream that is a delta from an earlier poll. 

> * Can you point me in the right direction where to setup some debugging points? I put some breakpoints in the ld_common_client.dart and it seems that the future in the _start function `return _startFuture!.then(_mapIdentifyStart); ` is never returned. But I'd like to dig deeper.

In the data_source_manager we handle messages from the data source:
```
          var handled = await _dataSourceEventHandler.handleMessage(
              _activeContext!, event.type, event.data);
          if (handled == MessageStatus.messageHandled &&
              _identifyCompleter != null) {
            if (_identifyCompleter!.isCompleted) {
              _logger.error('Identify was already complete before receiving '
                  'data. This could represent an issue with SDK logic. Please'
                  'make a bug report if you encounter this situation.');
            } else {
              _identifyCompleter!.complete();
            }
          }
```

_identifyCompleter is ultimately what resolves the identify process. So if we ever get any event which we are capable of handling from our data source (streaming or polling), then we complete the identify.

The sse_client_html is the SSE client that should be used on the web. It just uses the browser EventSource. 
This method should be called whenever it gets data: 
```
  void _handleMessageEvent(html.Event event) {
    _activeSince = DateTime.now().millisecondsSinceEpoch;
    final messageEvent = event as html.MessageEvent;
    final ldMessageEvent = ld_message_event.MessageEvent(
        messageEvent.type, messageEvent.data, messageEvent.lastEventId);
    _messageEventsController.sink.add(ldMessageEvent);
  }
```

> I have a small hypothesis that it could be due to my computer's VPN/firewall and its interaction with streams, but not certain.

It is possible, and I would be interested to know for future troubleshooting. Usually these don't block the initial connection, but sometimes can interfere with receiving updates, which results in periodic reconnects. 


Thank you,
Ryan

**Comment by ranganaperera** [comment]
@jturak-rbi I faced a similar timeout issue and it turned out I was passing in the `mobile sdk` key not `client id`. Could get the web to work with the key change. Make sure to expose your flags to `SDKs using Client-side ID` as well.

**Comment by kinyoklion** [comment]
@jturak-rbi Thank you. We will take a look at that. The credential should be invalid, which should result in a permanent failure instead of a timeout, but potentially we are handling something incorrectly in that case.
